[[main]]
    # Top-level menu entry
    identifier = "project"
    name = "Projects"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2


[[main]]
    # Top-level menu entry
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3
