### SEO, Analytics & 3rd-party
netlify_forms = false # add data-netlify attribute to contact and newsletter forms, false to disable Netlify forms
# gtm_id = '' # GTM tracking (leave blank to use GA)
disallow_search_engines = false # Disallow search engine crawling in robots.txt

### Content
author = 'Jamie' # Default author for <head> meta
avatar = 'icon.png' # Custom avatar image in /assets/
description = "A helpful AI Co-pilot in your device." # Add a global meta description to <head>
fallback_text = "No content available yet. Coming soon." # Fallback text for empty content
favicon = true # Enable favicon, add your favicon files to /static/ directory
footer_text = "Built with [Geeker AI](https://github.com/geeker-ai/hugo-liftoff) theme." # Customize footer text
grayscale_avatar = true # Add a grayscale filter to the avatar image
label_drafts = true # Add a label indicator next to the title of any built drafts (dev only)

# Customize newsletter text
global_newsletter = false # Enable newsletter site-wide
newsletter_description = "This is my custom newsletter description that tells you why you should sign up." 
newsletter_header = "This is my custom newsletter header with a captivating title." 
newsletter_submit = "Join now" 

# CSS / JavaScript
custom_css = 'custom.css' # Add the specified file to assets before setting this param to avoid errors
custom_js = 'custom.js' # Add the specified file to assets before setting this param to avoid errors
enable_postcss = false # Enable if you're using npm and want to utilize PostCSS processing

### Web schemas
# Open Graph
images = ['images/default.png'] # Fallback for Open Graph and Twitter Cards images if none are present in front matter. Enter path to the image. 
ogLocale = "en_US" # Open graph locale

# Twitter Cards
twitterCreator = "zmhu" # Enter your twitter handle without the @
twitterSite = "zmhu" # Enter your twitter handle without the @

# JSON-LD structured data schemas
schemaImage = "images/default.png" # Image for Person structured data schema. Enter path to the image.
schemaImageHeight = 455 # Height of the above image
schemaImageWidth = 453 # Width of the above image
schemaLocale = "en-US" # Structured data locale
schemaName = "Jamie" # Enter your name

### Social
# Show social links in footer, home hero section, or about page
about_page_socials = true
footer_socials = true
home_hero_socials = true

# Enable or disable individual social icons
[social.links]
email = "sammeyhu@gmail.com"
github = "geeker-ai"
# stack_overflow = "userid/username" # include user id
twitter = "zmhu"
# linkedin = "username" # Comment out to disable
# mastodon_server = "example.social" # include subdomains if relevant, scheme not needed (defaults to https)
# mastodon_user = "username" # don't include preceding @

# Enable or disable individual social share icons in posts
[social.share]
email = true
facebook = false
linkedin = false
reddit = false
twitter = true
